config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Pages routes
  root "pages#show", page: "home"
  get "/:page" => "pages#show"

  get 'admin/dashboard' => 'admin#dashboard'
  get 'admin/pages' => 'admin#pages'

  resources :pages, except: [:show], path: 'admin/page'
  resources :contacts, only: [:edit, :update], path: 'admin/contacts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contacts.rb
class Contacts < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :get_pages, :get_contacts
  layout 'admin'

  def dashboard
  end

  def pages
  end

  def get_pages
    @pages = Page.all
  end

  def get_contacts
    @contacts = Contacts.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  protect_from_forgery with: :exception

  def not_found
    redirect_to root_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :get_contacts, only: [:edit, :update]
  layout 'admin', only: [:edit, :update]

  def edit

  end

  def update
    permitted_columns = params.require(:contacts).permit(:full_name, :address, :email, :mobile, :rating)
    respond_to do |format|
      if @contacts.update_attributes(permitted_columns)
        format.html {
          redirect_to edit_contact_path(@contacts), notice: ['Update Complete', 'Contacts was successfully updated.']}
      end
    end
  end

  private

  def get_contacts
    @contacts = Contacts.first
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  rescue_from ActionView::MissingTemplate, with: :render_default_page
  before_action :current_page, only: [:edit, :update, :destroy]
  layout 'admin', only: [:edit, :update, :new]

  def show
    @page = Page.find_by!(slug: params[:page])
    render template: "pages/#{params[:page]}"
  end

  def render_default_page
    render template: 'pages/page'
  end

  def edit
  end

  def update
    permitted_columns = params.require(:page).permit(:title, :desc, :content)
    respond_to do |format|
      if @current.update_attributes(permitted_columns)
        format.html {
          redirect_to edit_page_path(@current),
                      notice: ['Update Complete', 'Page was successfully updated.',
                               "View #{view_context.link_to(@current.title, root_path + @current.slug)}"]}
      end
    end
  end

  def new
    @page = Page.new
  end

  def create
    permitted_columns = params.require(:page).permit(:title, :desc, :content, :slug)
    @page = Page.new(permitted_columns)

    respond_to do |format|
      if @page.save
        format.html { redirect_to root_path + @page.slug, notice: 'Page was successfully created.' }
      end
    end
  end

  def destroy
    @current.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Page was successfully destroyed.' }
    end
  end

  private

  def current_page
    @current = Page.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    Rails.application.class.parent_name
  end
end

app/views/admin/dashboard.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render  'shared/admin_sidebar' %>

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <h1 class="h2">Pages <small>(<%= @pages.count %>)</small></h1>
      <% unless notice.nil? %>
        <div class="alert alert-warning" role="alert">
          <p class="mb-0"><%= notice %></p>
        </div>
      <% end %>
      <table class="table table-striped">
        <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Title</th>
          <th>Created at</th>
          <th>Updated at</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @pages.limit(5).each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= item.title %></td>
            <td><%= item.created_at %></td>
            <td><%= item.updated_at %></td>
            <td>
              <%= link_to 'Edit', edit_page_path(item), class: 'btn btn-outline-primary btn-sm' %>
              <%= link_to(item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm') do %>
                Delete
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <div class="text-right">
        <%= link_to 'Add new page', new_page_path %>
        <a href="/admin/pages">View all</a>
      </div>

      <hr>

      <h2>Contacts</h2>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @contacts.full_name %></h5>
          <p class="card-text"><%= @contacts.address %></p>
          <ul class="list-group">
            <li class="list-group-item">Email address: <%= @contacts.email %></li>
            <li class="list-group-item">Mobile: <%= @contacts.mobile %></li>
            <li class="list-group-item">Rating: <%= @contacts.rating %></li>
          </ul>
          <br>
          <%= link_to 'Edit contacts',edit_contact_path(1), class: 'btn btn-primary' %>
        </div>
      </div>

      <br><br><br>
    </main>
  </div>
</div>

app/views/admin/pages.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render  'shared/admin_sidebar' %>

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <%= link_to 'Add new page', new_page_path, class: 'float-right btn btn-primary' %>
      <% unless notice.nil? %>
        <div class="alert alert-warning" role="alert">
          <p class="mb-0"><%= notice %></p>
        </div>
      <% end %>
      <h1 class="h2">Pages <small>(<%= @pages.count %>)</small></h1>
      <table class="table table-striped">
        <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Title</th>
          <th>Created at</th>
          <th>Updated at</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @pages.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= item.title %></td>
            <td><%= item.created_at %></td>
            <td><%= item.updated_at %></td>
            <td>
              <%= link_to 'Edit', edit_page_path(item), class: 'btn btn-outline-primary btn-sm' %>
              <%= link_to(item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm') do %>
                Delete
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </main>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render  'shared/admin_sidebar', :back_btn => true %>

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <% unless notice.nil? %>
        <div class="alert alert-success" role="alert">
          <h4 class="alert-heading"><%= notice.first %></h4>
          <p class="mb-0"><%= notice.last %></p>
        </div>
      <% end %>

      <%= form_for  @contacts do |f| %>
        <div class="form-group">
          <%= f.label :full_name %><br>
          <%= f.text_field :full_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :mobile %><br>
          <%= f.text_field :mobile, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :rating %><br>
          <%= f.text_field :rating, class: 'form-control' %>
        </div>

        <div class="form-group text-right">
          <%= f.submit 'Save changes', :class => 'btn btn-primary' %>
          <%= link_to 'Close', admin_dashboard_path , class: 'btn btn-link', role: 'button' %>
        </div>
      <% end %>
    </main>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stapp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="dashboard">
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Dashboard</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="narrow">
    <div class="container">
      <%= render 'shared/header' %>
      <%= yield %>

      <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js' %>
      <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js' %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for target do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <% if target.new_record? %>
    <div class="form-group">
      <%= f.label :slug %><br>
      <%= f.text_field :slug, class: 'form-control', :readonly => true %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :desc %><br>
    <%= f.text_field :desc, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 10, class: 'form-control' %>
  </div>

  <div class="form-group text-right">
    <% if target.new_record? %>
      <%= f.submit 'Create new page', :class => 'btn btn-primary' %>
    <% else %>
      <%= f.submit 'Update page', :class => 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Close', admin_dashboard_path , class: 'btn btn-link', role: 'button' %>
  </div>
<% end %>

app/views/pages/about.html.erb
<main role="main">
  <h1><%= @page.title %></h1>

  <%= @page.content.html_safe %>
</main>

app/views/pages/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render  'shared/admin_sidebar', :back_btn => true %>

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <% unless notice.nil? %>
        <div class="alert alert-success" role="alert">
          <h4 class="alert-heading"><%= notice.first %></h4>
          <p><%= notice.second %></p>
          <hr>
          <p class="mb-0"><%= sanitize(notice.last) %></p>
        </div>
      <% end %>
      <%= render 'form', {:target => @current} %>
    </main>
  </div>
</div>

app/views/pages/home.html.erb
<main role='main'>
  <div class='jumbotron'>
    <h1 class='display-3'><%= @page.title %></h1>
    <p class='lead'><%= @page.desc %></p>
    <p><a class='btn btn-lg btn-success' href='/services' role='button'>Our Services</a></p>
  </div>

  <%= @page.content.html_safe %>
</main>

app/views/pages/new.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render  'shared/admin_sidebar', :back_btn => true %>

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
      <%= render 'form', {:target => @page} %>
    </main>
  </div>
</div>

app/views/pages/page.html.erb
<main role="main">
  <% unless notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p class="mb-0"><%= notice %></p>
    </div>
  <% end %>

  <h1><%= @page.title %></h1>

  <%= @page.content.html_safe %>
</main>

app/views/shared/_admin_sidebar.html.erb
<nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
  <ul class="nav nav-pills flex-column">
    <% if local_assigns[:back_btn] %>
      <li class="nav-item">
        <%= link_to 'Back', admin_dashboard_path, class: 'btn btn-ligh btn-block' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Overview', admin_dashboard_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Pages', admin_pages_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contacts', edit_contact_path(1), class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_header.html.erb
<% pages = Page.all %>
<header class="header clearfix">
  <nav>
    <ul class="nav nav-pills float-right">
      <% current_url = request.path_parameters[:page] %>
      <% pages.limit(4).each do |item| %>
        <li class="nav-item">
          <%= link_to item.title, item.slug, class: "nav-link #{'active' if current_url === item.slug}" %>
        </li>
      <% end %>
      <% if pages.count > 4 %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% pages.drop(4).each do |item| %>
              <%= link_to item.title, item.slug, class: "dropdown-item #{'active' if current_url === item.slug}" %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </nav>
  <h3 class="text-muted"><%= app_name %></h3>
</header>